FROM ubuntu:latest
MAINTAINER fern
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /docker_practice
WORKDIR /docker_practice
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["fernapp.py"]
